### ISSUE TITLE
Login popup not responding on Firefox 54.0.1 (32 bit)

### ISSUE THREAD

**Issue by FajriFadli** [Chingu-cohorts/devgaido#74] opened 2017-07-24 11:02 UTC
**Issue Description & Expected Outcome:**
Login popup not responding after clicking either "Log in with Github" or "Log in with Google", get redirected to authorizing account permission from either Github or Google, and going back to http://www.devgaido.com by clicking the back button on browser. It can't be closed and the page need to be refreshed for it to work again. This issue doesn't seems to be present on Google Chrome 59.0.3071.115 (64 bit).

![2017-07-24 17_37_17-devgaido _ home](https://user-images.githubusercontent.com/20591663/28519999-026e625e-7098-11e7-8f97-c7a3b4540048.png)

**Symptoms:**
Login popup appears to be loading indefinitely while the X button used to close it doesn't work.

**Steps to Recreate:**
1. On Firefox, click login.
2. When the login popup appears, either click "Log in with Github" or "Log in with Google".
3. When you're redirected to authorizing account permission from either Github or Google, click the back button on the browser.
4. You'll be back on http://www.devgaido.com with the login popup not responding.

**Resolution:**
N/a

**Comment by jdmedlock** [comment] 2017-07-24 23:46
Thanks for catching this. During development up to this point we have primarily used Chrome 59. However, we'll change this to use at least Chrome, Safari, Firefox, and IE as part of our testing.

**Comment by kimkwanka** [comment] 2017-07-26 07:41
Can you give more information like which OS are you using and your location? I tested with Firefox 54.0.1 / Win 10 and it was working as expected for me.

**Comment by FajriFadli** [comment] 2017-07-28 12:43
I'm using Win 7 & my current location is in Jakarta, Indonesia. Tested it with Linux Mint on VirtualBox as well and the same problem persist.

**Comment by jdmedlock** [comment] 2017-07-29 13:15
@FajriFadli We have been unable to recreate this issue on both Manjaro Linux and MacOS. Would you check your Javascript console in Firefox and let us know if it contains any error messages?

**Comment by kimkwanka** [comment] 2017-07-29 13:20
@FajriFadli Additionally, can you try logging in to this (old) version of devgaido: https://devgaido.blackcroft.com please?

**Comment by FajriFadli** [comment] 2017-08-05 03:02
Sorry for the late respond. I've got hospitalized. Back to topic though, I don't have any warning or error messages in my Javascript console. It only notifies me that the site uses scroll-linked positioning effect.

**Comment by jdmedlock** [comment] 2017-08-05 11:38
On MacOS the console log contains the following when the 'Login' button is pressed. However, the message is removed from the log after pressing 'Login with Google' from the Auth0 dialog. 
```

          Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://devgaido.auth0.com/user/ssodata/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)
"There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "https://www.devgaido.com" to the "Allowed Origins (CORS)" list in the Auth0 dashboard: https://manage.auth0.com/#/applications/L90m0rEGvEWnCkQOBYE3U30J6m68HDIb/settings"
```

**Comment by FajriFadli** [comment] 2017-08-08 15:09
Yes I have Add-ons installed, but I was testing with Add-ons disabled and still run into the same problem. I've also tested it with a different machine running on Win 10 but with older version of firefox and run into the same problem as well. I found this with the debugger though.
![2017-08-08 21_46_33-devgaido _ home](https://user-images.githubusercontent.com/20591663/29078186-d9421a9a-7c83-11e7-9257-6d2d5eaffb42.png)
I assume the bundle.js is the javascript used by the page? When the login popup not responding, the firefox debugger doesn't seem to detect the javascript as can be shown here
![2017-08-08 21_47_30-](https://user-images.githubusercontent.com/20591663/29078376-5f24d210-7c84-11e7-93ee-d5a386a72b0a.png)

**Comment by jdmedlock** [comment] 2017-08-11 12:39
@FajriFadli We are puzzled by this error since we have been unable to recreate this issue. Would you please check your network tab in the Firefox developer tools to see if there are any messages? Also, could there be any firewall or anti-virus rules preventing the API call to Auth0?

**Comment by jdmedlock** [comment] 2017-08-20 00:32
A screen sharing session with @FajriFadli revealed that the issue is caused by clicking on the browser from the Google authentication page - before completing authentication.  I was able to find a similar issue on Auth0's support forum stating that this behavior is unavoidable due to how the OAuth protocol is designed and implemented (https://community.auth0.com/questions/2523/social-login-back-button). While there are some possible ways to handle this, such as a custom error page, there are side effects. 

Since this is an edge case we are closing this issue without resolution, but will reopen if sufficient demand arises.

**Closed by jdmedlock** 2017-08-20 00:32 UTC
Labels: MVP1, type: bug
